name: test_env_xgcm_docs
dependencies:
  - python=3.9
  - numba
  - pandoc
  - sphinx<5
  - pip
  - pip:
    - netcdf4
    - cartopy
    - matplotlib
    - nbsphinx
    - numpydoc
    - sphinxcontrib-applehelp<1.0.5
    - sphinxcontrib-devhelp<1.0.6
    - sphinxcontrib-htmlhelp<2.0.5
    - sphinxcontrib-serializinghtml<1.1.10
    - sphinxcontrib-qthelp<1.0.7
    - pangeo-sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - sphinx-panels
    - sphinxcontrib-srclinks
    # - sphinx_rtd_theme
    # - sphinx-pangeo-theme
    # - ipykernel
    - ipython>=8.5.0
    - nbsphinx
    # - jupyter_client


