name: test_env_xgcm_docs
dependencies:
  - python=3.9
  - xarray
  - netcdf4
  - cartopy
  - dask
  - numpy
  - numba
  - future
  - pytest
  - numpydoc
  - sphinx
  - matplotlib
  - sphinx_rtd_theme
  - ipykernel
#  - python-graphviz
  - pip:
    - nbsphinx
    - jupyter_client
    - pangeo-sphinx-book-theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
    - sphinx-panels
    - git+https://github.com/TomNicholas/ipython.git@dont_strip_all_decorators2
