name: test_env_xgcm_docs
dependencies:
  - python
  - xarray
  - netcdf4
  - cartopy
  - dask
  - numpy
  - numba
  - future
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - sphinx_rtd_theme
  - ipykernel
  - pip:
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
