name: xgcm
dependencies:
  - python=3.6
  - xarray
  - netcdf4
  - dask
  - numpy
  - future
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - pip:
    - docrep
    - nbsphinx
    - jupyter_client
