name: test_env_xgcm
dependencies:
  - python=3.7
  - xarray
  - dask
  - numpy
  - numba<=0.48
  - pytest
  - future
  - pip
  - black
  - pip:
    - docrep<=0.2.7
    - codecov
    - pytest-cov
    - pytest-xdist

