name: publish-to-twitter
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: infraway/tweet-action@v1
        with:
          status: Tweeted from Github Actions
          api_key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          api_key_secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET}}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
